version: '3'
services:
  postgres:
    image: postgres:9.6.1
    ports:
      - 5422:5432
    environment:
      - POSTGRES_DB=task-manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres